import { useState } from 'react';
import { InspectImage } from './InspectImage';
import { K } from './StudyKit';
const scenes=[{name:'Today',title:'A little encouragement.',text:'See who’s already been out and who still has today. There’s room for a cheer, without turning the family into a leaderboard.',file:'today'}, {name:'The week',title:'Every day adds up.',text:'The weekly trail makes everyone’s effort visible. A rest day can belong in the story too.',file:'trail'}, {name:'A milestone',title:'A moment worth keeping.',text:'Thirty mornings becomes a shared memory. The milestone gets its own quiet, celebratory treatment.',file:null}];
export default function ArroStudy(){const [step,setStep]=useState(0);const [cheered,setCheered]=useState(false);const scene=scenes[step];
  return <article className="ps-arro"><header className="ps-arro__hero"><svg className="pa-trail" viewBox="0 0 1200 560" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><path pathLength="1" d="M-40 470 C 180 330, 330 520, 560 380 S 900 140, 1260 230"/>{[[190,372],[430,440],[640,338],[880,215],[1090,196]].map(([x,y],i)=><circle key={i} cx={x} cy={y} r="13" style={{'--i':i} as React.CSSProperties}/>)}</svg><div className="ps-arro__title"><span className="ps-eyebrow">Arro / A family running ritual</span><h1 tabIndex={-1}><K>Every day</K><br/><K at={2}>forward.</K><br/><em><K at={3}>Together.</K></em></h1><p>A small reason to show up.<br/>Five people to share it with.</p><div className="ps-arro__family" aria-hidden="true">{['A','S','K','R','L'].map(letter=><span key={letter}>{letter}</span>)}</div><span className="ps-arro__label">Product design · React Native prototype</span></div><div className="ps-arro__preview"><div className="ps-arro__phone" key={step}>{scene.file?<img src={`/projects/arro/${scene.file}-sample.png`} alt={`Arro ${scene.name.toLowerCase()} design frame with sample family activity`}/>:<div className="ps-arro__milestone"><span>Arro / A moment to keep</span><strong>30</strong><span>mornings, together.</span><p>Alex kept 30 days.<br/>The family’s cheering.</p><button aria-pressed={cheered} onClick={()=>setCheered(!cheered)}>{cheered?'♥ Cheer sent':'♡ Send a sample cheer'}</button><small>Illustrative milestone interaction</small></div>}</div><small className="ps-sample-note">Prototype with sample activity. Names and initials are fictional.</small><nav className="ps-arro__tabs" aria-label="Arro story">{scenes.map((item,index)=><button key={item.name} aria-pressed={step===index} onClick={()=>setStep(index)}><small>0{index+1}</small>{item.name}</button>)}</nav></div></header>
    <section className="ps-arro__moment" aria-live="polite"><span className="ps-eyebrow">0{step+1} / 03</span><h2>{scene.title}</h2><p>{scene.text}</p>{scene.file&&<InspectImage src={`/projects/arro/${scene.file}-sample.png`} alt={`Arro ${scene.name.toLowerCase()} design frame`}/>}</section>
    <section className="ps-editorial"><span className="ps-eyebrow">Built around a shared habit</span><h2>Make the habit<br/>feel human.</h2><p>Running apps can make every kilometre feel like a comparison. Arro starts with a different question: how do we help each other keep going?</p><div className="ps-editorial__pair"><div><span className="ps-eyebrow">Design</span><h3>Encouragement over rankings.</h3><p>Warm colour, familiar faces and a simple daily state. Each screen gives the family something to notice or celebrate.</p></div><div><span className="ps-eyebrow">Engineering</span><h3>Give the ritual a rhythm.</h3><p>The Expo and React Native prototype connects Today, the Trail, family activity and milestone screens around shared fixture data. The visual system carries through its navigation and small interactions.</p></div></div></section>
    <footer className="ps-study-footer"><div>Product design & mobile implementation<br/>Bryce Rambach</div><p>Prototype with sample activity. Names and initials are fictional. Today and the week are captured design frames with initial avatars. The milestone is an enlarged portfolio interpretation. Cheers stay in this demo. No backend or Strava connection is executed.</p></footer>
  </article>;
}
