import { useState } from 'react';
import { InspectImage } from './InspectImage';
import { K } from './StudyKit';
const mappings=[
  {from:'firstName',to:'firstName',source:'Knowledge base',state:'Verified',detail:'The preview marks this direct name mapping as verified against its knowledge-base entry.'},
  {from:'email',to:'work.email',source:'Knowledge base',state:'Verified',detail:'The sample mapping lowercases the email value before assigning it to work.email.'},
  {from:'hireDate',to:'startDate',source:'Knowledge base',state:'Verified',detail:'The date is converted to ISO format. The transformation travels with the field mapping.'},
  {from:'department',to:'work.department',source:'Research',state:'Researched',detail:'The preview records a name-based department match. It also flags the risk that a renamed department could break it.'},
  {from:'customField.c_super',to:'work.customColumns.super',source:'Model inference',state:'Inferred',detail:'This field is inferred in the source fixture. It needs review before you rely on the destination field.'},
];
export default function LucidStudy(){const [field,setField]=useState(4);const [held,setHeld]=useState(false);const [step,setStep]=useState(0);const mapping=mappings[field];
  return <article className="ps-lucid"><header className="ps-lucid__hero"><span className="ps-eyebrow">Lucid / Integration workspace</span><h1 tabIndex={-1}><K>Clarity,</K><br/><em><K at={1}>field by field.</K></em></h1><div className="ps-lucid__intro"><p>Turn a request into something<br/>you can inspect, question and build.</p><span>Product design & engineering<br/>Development prototype</span></div><div className="pl-chips" aria-hidden="true">{mappings.map((m,i)=><span key={m.from} className={`pl-chip is-${m.state.toLowerCase()}`} style={{'--i':i} as React.CSSProperties}>{m.from}<i>→</i>{m.to}</span>)}</div><div className="ps-lucid__route" aria-hidden="true"><span>Request</span><i/><span>Mapping</span><i/><span>Specification</span></div></header>
    <section className="ps-lucid__demo" aria-label="Lucid sample specification"><nav aria-label="Lucid demonstration">{['The request','Inspect a field','Review the scope'].map((name,index)=><button key={name} aria-pressed={step===index} onClick={()=>setStep(index)}><small>0{index+1}</small>{name}</button>)}</nav>
      {step===0?<div className="ps-lucid__brief"><span className="ps-eyebrow">Illustrative brief</span><h2>Keep our employee<br/>records in sync.</h2><p>Move new and updated employee records from NetSuite to HiBob each night. Skip contractors. Match departments and make the field transformations explicit.</p><button onClick={()=>setStep(1)}>Follow the mapping</button><small>Based on the source specification preview. Verified, researched and inferred are fixture labels, not checks performed by this portfolio. No systems are connected.</small></div>:step===1?<div className="ps-lucid__mapping"><div className="ps-lucid__fields"><span className="ps-eyebrow">Source → Destination</span>{mappings.map((item,index)=><button key={item.from} aria-pressed={field===index} onClick={()=>setField(index)}><span>{item.from}<i>→</i>{item.to}</span><small className={`is-${item.state.toLowerCase()}`}>{item.state}</small></button>)}</div><aside><span className="ps-eyebrow">{mapping.source} / fixture</span><h2>{mapping.state}.</h2><p>{mapping.detail}</p><small className="ps-sample-note">Verified, researched and inferred are fixture labels, not checks performed by this portfolio.</small>{field===4&&<button aria-pressed={held} onClick={()=>setHeld(!held)}>{held?'Return field to scope':'Hold this field for review'}</button>}<span className="ps-lucid__local-status" role="status">{held?'One field held for review in this example.':'Select a field to inspect its reasoning.'}</span><button className="ps-lucid__review-link" onClick={()=>setStep(2)}>Review the sample scope →</button></aside></div>:<div className="ps-lucid__review"><span className="ps-eyebrow">Sample scope / Review</span><h2>{held?'Four fields included.':'Five fields proposed.'}<br/><em>{held?'One question preserved.':'One inference to check.'}</em></h2><div><p>{held?'The inferred field is held outside the sample scope. The unresolved mapping stays visible for the next review.':'The proposed scope still includes an inferred destination. It should remain a visible review question, even beside four better-supported mappings.'}</p><dl><div><dt>Included fields</dt><dd>{held?'04':'05'}</dd></div><div><dt>Held for review</dt><dd>{held?'01':'00'}</dd></div><div><dt>Live execution</dt><dd>None</dd></div></dl></div><button onClick={()=>{setStep(1);setField(4);}}>Return to the inference</button></div>}
    </section>
    <section className="ps-lucid__capture"><div><span className="ps-eyebrow">From the working preview</span><h2>Every value<br/>carries its source.</h2><p>The specification brings fields, transformations and risk into one readable document.</p><InspectImage src="/projects/lucid/mapping.png" alt="Lucid specification preview with sample mappings and risk"/></div><img src="/projects/lucid/mapping.png" alt="Original Lucid preview showing five mappings with their evidence categories" loading="lazy"/></section>
    <section className="ps-editorial"><span className="ps-eyebrow">The design decision</span><h2>Make assumptions<br/>easy to find.</h2><p>Integrations get complicated at the boundaries: field names, formats and the assumptions between them. Lucid gives those details an explicit place in the work.</p><div className="ps-editorial__pair"><div><span className="ps-eyebrow">Product</span><h3>A continuous piece of work.</h3><p>Conversation, scope, specification, builds and runs form one product direction. This demonstration focuses on the source-backed specification and field-review experience.</p></div><div><span className="ps-eyebrow">Engineering</span><h3>Data with its reasoning attached.</h3><p>The Next.js source represents mappings with their transformations, confidence labels and notes. The review example above adapts that fixture into a small, explorable sequence.</p></div></div></section>
    <footer className="ps-study-footer"><div>Product design & implementation<br/>Bryce Rambach</div><p>Development prototype. Captures use the built-in specification preview. Verified, researched and inferred are fixture labels, not checks performed by this portfolio. The field-hold interaction is illustrative. No APIs, credentials or customer data are used.</p></footer>
  </article>;
}
